/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as narratorGpt4TuboSol from './Narrator-GPT4-Tubo.sol'
export type { narratorGpt4TuboSol }
import type * as narratorOpusSol from './Narrator-Opus.sol'
export type { narratorOpusSol }
import type * as narratorSol from './Narrator.sol'
export type { narratorSol }
import type * as interfaces from './interfaces'
export type { interfaces }
export * as factories from './factories'
export type { IChatGpt } from './interfaces/IChatGpt'
export { IChatGpt__factory } from './factories/interfaces/IChatGpt__factory'
export type { IOracle } from './interfaces/IOracle'
export { IOracle__factory } from './factories/interfaces/IOracle__factory'
export type { PlaybookNarrator } from './Narrator-GPT4-Tubo.sol/PlaybookNarrator'
export { PlaybookNarrator__factory } from './factories/Narrator-GPT4-Tubo.sol/PlaybookNarrator__factory'
