/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as narratorGpt4TuboSol from './Narrator-GPT4-Tubo.sol'
export * as narratorOpusSol from './Narrator-Opus.sol'
export * as narratorSol from './Narrator.sol'
export * as interfaces from './interfaces'
