/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as narratorGpt4TurboSol from './Narrator-GPT4-Turbo.sol'
export * as narratorLlama80BSol from './Narrator-Llama80B.sol'
export * as narratorOpusSol from './Narrator-Opus.sol'
export * as narratorSol from './Narrator.sol'
export * as interfaces from './interfaces'
